refactor stream constructor for CUDArt
JuliaGPU/CUDAdrv.jl pull request #17
Opened 2017-02-17 14:51 UTC by vchuravy

2017-02-17 15:56 UTC, maleadt commented
Why is this necessary? Especially after https://github.com/JuliaGPU/CUDArt.jl/pull/62?

2017-02-17 15:58 UTC, maleadt requested changes

2017-02-17 15:58 UTC, maleadt commented on src/stream.jl
> +    CuStream(handle::CuStream_t, ctx::CuContext, _) = new(handle, ctx)
Why is this necessary? I don't really like having such a three-argument ctor where the third argument is ignored...

2017-02-17 16:47 UTC, vchuravy commented
We have no constructor that just takes a handle: https://github.com/JuliaGPU/CUDArt.jl/blob/a6cf291d09adee29d4a36ec8742c4c4e947ffd13/src/stream.jl#L16

2017-02-18 07:39 UTC, vchuravy commented on src/stream.jl
> +    CuStream(handle::CuStream_t, ctx::CuContext, _) = new(handle, ctx)
I originally wanted to define:
```
CuStream() = new(convert(CuStream_t, C_NULL), C_NULL)
```

but that is ambiguous with the `flags::Integer=0`

2017-02-27 12:03 UTC, closed without merging