Primary contexts for CUDArt
JuliaGPU/CUDAdrv.jl pull request #19
Opened 2017-02-27 04:55 UTC by vchuravy

This adds the necessary infrastructure to handle primary contexts improving interaction between CUDArt and CUDAdrv.

2017-02-27 05:44 UTC, vchuravy commented
Rebased onto current master and added tests.

2017-02-28 06:44 UTC, vchuravy commented
Once we have reset a context or destroyed it we should no longer free any resources attached to it since they will be destroyed already by the driver. In the case of primary contexts the story is a bit more complicated, because a reset followed by a retain will give you a valid context at the same address, so the driver will not throw an error (since there is a valid context) but will seqfault if you free a previous attached resource....

@maleadt if you are ok with this approach I will extend this to the other managed resources.

2017-02-28 06:48 UTC, maleadt commented
Right. This would also protect against ouf-of-order finalizers (where contexts are finalized before their resources), making `can_finalize` redundant.

2017-02-28 07:00 UTC, vchuravy commented
Yeah I was hoping that there would be an API to query if a context is still valid, but even that wouldn't work in the primary context case... I am not certain if we can replace can_finalize with this but it might be worth a try.

Should we fold owned and isvalid into a single bitmask field?

2017-02-28 07:19 UTC, maleadt commented
> Should we fold owned and isvalid into a single bitmask field?
Nah, that's micro-optimization for an object that's pretty heavy to allocate anyway. A more sensible optimization would be to cache `CuCurrentContext`, but that's for another time and PR.

2017-02-28 07:27 UTC, vchuravy commented
The test failure only happens if I run julia with `--compilecache=yes`

2017-02-28 07:46 UTC, vchuravy commented
CUDAnative test pass locally.

2017-02-28 08:15 UTC, vchuravy commented
squashed commits, CUDAnative and CUDAdrv both pass tests.

2017-02-28 08:39 UTC, maleadt commented
Ha, you went quite a bit further than I intended, ripping out _all_ of `gc.jl` instead of just the out-of-order finalization check (the `block` methods were intended to _force_ in-order finalization). But, on the other hand, why not... Even if we trigger more out-of-order finalizer runs that way, they'll all be valid and tearing down the context takes care of destroying everything anway.

2017-02-28 09:08 UTC, vchuravy commented
Oh yeah... I just thought that keeping two systems that do the same thing
is kinda pointless ;)

On Tue, 28 Feb 2017, 17:39 Tim Besard, <notifications@github.com> wrote:

> Ha, you went quite a bit further than I intended, ripping out *all* of
> gc.jl instead of just the out-of-order finalization check (the block
> methods were intended to *force* in-order finalization). But, on the
> other hand, why not... Even if we trigger more out-of-order finalizer runs
> that way, they'll all be valid and tearing down the context takes care of
> destroying everything anway.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/JuliaGPU/CUDAdrv.jl/pull/19#issuecomment-282976984>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAI3aouCi0GIZP6Xco0pZR9SvUOZbTwaks5rg91VgaJpZM4MMsZm>
> .
>

2017-03-01 13:36 UTC, vchuravy commented
Rebase onto master again, hopefully I adapted to the test changes correctly. Tests pass locally.

2017-03-01 13:59 UTC, maleadt requested changes
Great, thanks! Some minor nitpicks. Merge/tag at your will.

2017-03-01 13:59 UTC, maleadt commented on src/module.jl
> +    function CuModule(data, options::Dict{CUjit_option,Any}=Dict{CUjit_option,Any}(); ctx = CuCurrentContext())
Why do you do this? We do an API call to load the module data in this ctor, so it can't be that the context is anything else than the default one?

2017-03-01 13:59 UTC, maleadt commented on src/module.jl
> +CuModuleFile(path, ctx = CuCurrentContext()) = CuModule(open(readstring, path); ctx = ctx)
idem

2017-03-01 13:59 UTC, maleadt commented on src/util/logging.jl
> +    TRACE && return esc(Expr(:call, :(CUDAdrv.trace), args...))
Nice catch. Might be better to keep the `esc` fine grained though: leave the `trace` unescaped, and pass `$(map(esc, args)...)`

2017-03-01 13:59 UTC, maleadt commented on src/util/logging.jl
> +    DEBUG && return esc(Expr(:call, :(CUDAdrv.trace), args...))
idem

2017-03-01 14:32 UTC, merged