Wrap functionality to set and query stream priorities.
JuliaGPU/CUDAdrv.jl pull request #237
Opened 2020-05-01 11:50 UTC by maleadt

Fixes https://github.com/JuliaGPU/CUDAdrv.jl/issues/146

2020-05-01 15:13 UTC, maleadt commented
cc @samo-lin, could you have a look?

2020-05-04 10:57 UTC, samo-lin requested changes
Once this little fix of the argument type of CuStream is done it seems all perfectly fine. Using my local fix, I could successfully overlap two streams using the following code (overlap verified with nvvp):
```
using CUDAdrv, CUDAnative, CuArrays

function memcopy!(A, B)
    ix = (blockIdx().x-1) * blockDim().x + threadIdx().x
    A[ix] = B[ix]
    return
end

nx = 128*1024^2
nt = 100
A = CuArrays.zeros(nx);
B = CuArrays.ones(nx);
C = CuArrays.zeros(nx);
D = CuArrays.ones(nx);
nthreads = 1024
nblocks = ceil(Int, nx/nthreads)

p_range = priority_range();
s1 = CuStream(; flags=CUDAdrv.STREAM_NON_BLOCKING, priority=p_range[1])
s2 = CuStream(; flags=CUDAdrv.STREAM_NON_BLOCKING, priority=p_range[end])

priority(s1)
priority(s2)

for it = 1:nt
    @cuda blocks=nblocks threads=nthreads stream=s1 memcopy!(A, B);
    @cuda blocks=nblocks threads=nthreads stream=s2 memcopy!(C, D);
    CUDAdrv.synchronize()
end
```

2020-05-04 10:57 UTC, samo-lin commented on src/stream.jl
> +                    priority::Union{Nothing,Int}=nothing)
In my simple test, where I gave priorities obtained from `priority_range()` to `CuStream` it failed with this error:
```
omlins@nid00003:~/.julia/1.4.1/dom-gpu/dev/CUDAdrv> julia
    
julia> using CUDAdrv, CUDAnative, CuArrays

julia> p_range = priority_range();


julia> s1 = CuStream(; flags=CUDAdrv.STREAM_NON_BLOCKING, priority=minimum(p_range))
ERROR: TypeError: in keyword argument priority, expected Union{Nothing, Int64}, got Int32
Stacktrace:
 [1] top-level scope at REPL[3]:1
```
I think the elements obtained from the output of `priority_range()` should not require any type conversion when passing them to `CuStream`. Maybe  to do just `priority::Union{Nothing,Integer}=nothing` would be fine (after I changed this the CuStream was successfully created)?

2020-05-04 11:18 UTC, maleadt commented on src/stream.jl
> +                    priority::Union{Nothing,Int}=nothing)
Yes, that makes sense. Thanks for looking it over!

2020-05-04 11:27 UTC, merged

2020-05-04 13:14 UTC, samo-lin commented
Thanks @maleadt !!